"""Product SubType Migration

Revision ID: 0737e26b3106
Revises: 093fd10d6a05
Create Date: 2025-07-24 20:12:49.111129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0737e26b3106'
down_revision: Union[str, Sequence[str], None] = '093fd10d6a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_sub_type', sa.String(length=35), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_sub_type')
    # ### end Alembic commands ###
