"""Product Type Migration

Revision ID: 093fd10d6a05
Revises: dc8ac38e8191
Create Date: 2025-07-22 19:31:17.357616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093fd10d6a05'
down_revision: Union[str, Sequence[str], None] = 'dc8ac38e8191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_type', sa.Enum('technology', 'clothing', 'accessories', 'beauty', 'sports', name='producttype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_type')
    # ### end Alembic commands ###
