"""Fixed Migration

Revision ID: 6ad6e90c33e4
Revises: 95c2dd7e2e6d
Create Date: 2025-07-29 18:41:29.488071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad6e90c33e4'
down_revision: Union[str, Sequence[str], None] = '95c2dd7e2e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('finished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'finished')
    # ### end Alembic commands ###
