"""OrderItem Migration

Revision ID: 95c2dd7e2e6d
Revises: 5dcdf05b3559
Create Date: 2025-07-29 14:17:50.327105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c2dd7e2e6d'
down_revision: Union[str, Sequence[str], None] = '5dcdf05b3559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###
